### PR TITLE
Feature leaderboard page

### PR DESCRIPTION
**Pull request by DylanWarrener**
Leaderboards page...little boring but didn't know what else to add?!

### CODE REVIEW

**Comment by luk707** [comment]
It's saying that this commit has conflicts Dylan, I'll have a look at it when I've finished work

**Comment by DylanWarrener** [comment]
I think it may be because I have added the html tags I.e doctype

**Comment by luk707** [comment]
Ive just had a look and I am going to try and resolve the conflict however just so you are aware, these are partial HTML files meaning they will be embedded within another HTML file that already has all of the HTML boilerplate code i.e. the body, head and title etc. Ill give you a bell as soon as I have done this but you will still need to fix it before I approve it.

**Comment by luk707** [comment]
All resolved, just need to remove the extra stuff.

**Review by luk707 — CHANGES_REQUESTED** [review]
Remove the boilerplate HTML around leaderboard.component.html as it is a partial file

**Comment by luk707** [comment]
Just made a quick change, the leaderboard data is no longer hard coded into the HTML

**Comment by DylanWarrener** [comment]
Right okay

**Review by luk707 — APPROVED** [review]
Looks good now

**Pull request merged**
